version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    hostname: rabbitmq
    tty: true
    env_file:
      - ./.env
    volumes:
      - /var/lib/rabbitmq
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    restart: unless-stopped
    networks:
      - queue

networks:
  queue:
    driver: bridge
